export const tickets = [
  {
    id: 1,
    title: "VISITOR 3 DAY ACCESS TICKET",
    headerColor: "bg-purple-gradient",
    badge: null,
    price: "USD 32.5",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [],
    priceLabel: "INCL. 20% VAT",
    isPaid: true,
    quantity: 25,
    overlayImg: "Overlay1",
  },
  {
    id: 2,
    title: "VISITOR 3 DAY ACCESS TICKET",
    headerColor: "bg-orange-gradient",
    badge: null,
    price: "FREE",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "Access to Connexions & Investor Lounge", isDisabled: false },
      { name: "Network Events", isDisabled: false },
      { name: "All Conference Tracks", isDisabled: false },
      { name: "All Masterclasses", isDisabled: false },
      { name: "3 Days Access to the Show", isDisabled: false },
      { name: "Access to Dubai Internet City Lounge", isDisabled: false },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: false,
    overlayImg: "Overlay2",
  },
  {
    id: 3,
    title: "VISITOR 3 DAY ACCESS TICKET",
    headerColor: "bg-green-dark-gradient",
    badge: { text: "EXCLUSIVE" },
    price: "FREE",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "Access to Connexions & Investor Lounge", isDisabled: false },
      { name: "Network Events", isDisabled: false },
      { name: "All Conference Tracks", isDisabled: false },
      { name: "All Masterclasses", isDisabled: false },
      { name: "3 Days Access to the Show", isDisabled: true },
      { name: "Access to Dubai Internet City Lounge", isDisabled: true },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: false,
    overlayImg: "Overlay3",
  },
  {
    id: 4,
    title: "VISITOR 3 DAY ACCESS TICKET",
    headerColor: "bg-red-gradient",
    badge: { text: "BEST SELLER" },
    price: "FREE",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "Access to Connexions & Investor Lounge", isDisabled: false },
      { name: "Network Events", isDisabled: false },
      { name: "All Conference Tracks", isDisabled: false },
      { name: "All Masterclasses", isDisabled: false },
      { name: "3 Days Access to the Show", isDisabled: false },
      { name: "Access to Dubai Internet City Lounge", isDisabled: false },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: false,
    overlayImg: "Overlay2",
  },
  {
    id: 5,
    title: "VISITOR 3 DAY ACCESS TICKET",
    headerColor: "bg-green-light-gradient",
    badge: null,
    price: "FREE",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "Access to Connexions & Investor Lounge", isDisabled: false },
      { name: "Network Events", isDisabled: false },
      { name: "All Conference Tracks", isDisabled: false },
      { name: "All Masterclasses", isDisabled: false },
      { name: "3 Days Access to the Show", isDisabled: false },
      { name: "Access to Dubai Internet City Lounge", isDisabled: false },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: false,
    overlayImg: "Overlay2",
  },
  {
    id: 6,
    title: "VISITOR 3 DAY ACCESS TICKET",
    headerColor: "bg-blue-gradient",
    badge: null,
    price: "FREE",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "Access to Connexions & Investor Lounge", isDisabled: false },
      { name: "Network Events", isDisabled: false },
      { name: "All Conference Tracks", isDisabled: false },
      { name: "All Masterclasses", isDisabled: false },
      { name: "3 Days Access to the Show", isDisabled: true },
      { name: "Access to Dubai Internet City Lounge", isDisabled: true },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: false,
    overlayImg: "Overlay3",
  },
];
export const workshopList = [
  "Global Leaders Forum (1 Day)",
  "GITEX Main Stage",
  "Artificial Intelligence & Robotics (1)",
  "Future Health NEW (2 Days)",
  "Cybersecurity (1 Day)",
  "Future Health !NEW (2 Days)",
  "AI Everything (4 Days)",
  "Future Health !NEW (3 Days)",
];
