export const tickets = [
  {
    id: 1,
    title: "VISITOR 1 DAY ACCESS TICKET",
    headerColor: "bg-purple-gradient",
    badge: null,
    price: 82.5,
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [],
    priceLabel: "INCL. 20% VAT",
    isPaid: true,
    quantity:1,
    overlayImg: "Overlay1",
  },
  {
    id: 2,
    title: "VISITOR 2 DAY ACCESS TICKET",
    headerColor: "bg-orange-gradient",
    badge: null,
    price: 72,
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "VISITOR 2 spec day 1", isDisabled: false },
      { name: "VISITOR 2 day spec 2", isDisabled: false },
      { name: "VISITOR 2 spec 3", isDisabled: false },
      { name: "VISITOR 2 day spec 4", isDisabled: false },
      { name: "VISITOR 2 spec  day 5", isDisabled: false },
      { name: "VISITOR 2 spec 6", isDisabled: false },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: 0,
    overlayImg: "Overlay2",
  },
  {
    id: 3,
    title: "VIP 3 DAY ACCESS TICKET",
    headerColor: "bg-green-dark-gradient",
    badge: { text: "EXCLUSIVE" },
    price: 95,
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "VIP DAY spec 1", isDisabled: false },
      { name: "VIP 3 DAY spec 2", isDisabled: false },
      { name: "VIP 3 spec 3", isDisabled: false },
      { name: "VIP 3 DAY 4", isDisabled: false },
      { name: "VIP 3 spec 5", isDisabled: true },
      { name: "VIP 6", isDisabled: true },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: 0,
    overlayImg: "Overlay3",
  },
  {
    id: 4,
    title: "FAMILY PACK 4 DAY  TICKET",
    headerColor: "bg-red-gradient",
    badge: { text: "BEST SELLER" },
    price: 180,
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "FAMILY PACK 1", isDisabled: false },
      { name: "FAMILY PACK spec 2", isDisabled: false },
      { name: "FAMILY PACK DAY  3", isDisabled: false },
      { name: "FAMILY PACK 4 DAY spec 4", isDisabled: false },
      { name: "FAMILY PACK spec 5", isDisabled: false },
      { name: "FAMILY PACK spec 6", isDisabled: false },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity:0,
    overlayImg: "Overlay2",
  },
  {
    id: 5,
    title: "EARLY BIRD ACCESS TICKET",
    headerColor: "bg-green-light-gradient",
    badge: null,
    price: "76.08",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "EARLY BIRD  1", isDisabled: false },
      { name: "EARLY BIRD ACCESS  2", isDisabled: false },
      { name: "EARLY BIRD ACCESS spec 3", isDisabled: false },
      { name: "EARLY BIRD  spec 4", isDisabled: false },
      { name: "EARLY BIRD ACCESS  5", isDisabled: false },
      { name: "EARLY BIRD  6", isDisabled: false },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: 0,
    overlayImg: "Overlay2",
  },
  {
    id: 6,
    title: "LATE ENTRY ACCESS TICKET",
    headerColor: "bg-blue-gradient",
    badge: null,
    price: "91.05",
    includesVat: true,
    description: {
      first: "Visitor Passes provide ",
      second: "3 DAYS ACCESS ",
      third: "to GITEX NIGERIA exhibition and all free conference",
    },
    features: [
      { name: "LATE ENTRY ACCESS  1", isDisabled: false },
      { name: "LATE ENTRY day spec 2", isDisabled: false },
      { name: "LATE ENTRY day 3", isDisabled: false },
      { name: "LATE ENTRY ACCESS spec 4", isDisabled: false },
      { name: "LATE ENTRY  5", isDisabled: true },
      { name: "LATE ENTRY ACCESS  6", isDisabled: true },
    ],
    priceLabel: "INCL. 19% VAT",
    isPaid: false,
    quantity: 0,
    overlayImg: "Overlay3",
  },
];
export const workshopList = [
  "Global Leaders Forum (1 Day)",
  "GITEX Main Stage",
  "Artificial Intelligence & Robotics (1)",
  "Future Health NEW (2 Days)",
  "Cybersecurity (1 Day)",
  "Future Health !NEW (2 Days)",
  "AI Everything (4 Days)",
  "Future Health !NEW (3 Days)",
];
